
name: Deploy api (prod)

on:
  push:
    branches:
      - master
    paths:
      - apps/api/**
      - libs/**

jobs:

  build-and-test:
    name: Install dependencies, build libs & test libs and api app
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      # setup node version
      matrix:
        node-version: [12.x]
      
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2

      # use correct node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # cache node_modules
      - name: Cache node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # install dependencies
      - name: Install packages
        run: yarn install --frozen-lockfile

      # build libs
      - run: yarn build:libs

      # test libs & api code
      - name: Test project
        run: yarn test:libs & yarn test:api
        env:
          CI: true

  # deploy to netlify
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
    - uses: actions/checkout@v2

    # deploy to Heroku
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PROD_API }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: "master"
